### ISSUE TITLE
Installation and building instructions Windows

### ISSUE THREAD

**Issue by paul-ferragut** [elliotwoods/ofxCeres#13]
Could you share installation instructions on Windows?
I tried running the examples without success with the project generator, on windows visual studio 2022, of_v0.11.2 and the specified addons. I would love to try ofxCeres.
thanks!

**Comment by elliotwoods** [comment]
Please check the note at https://github.com/elliotwoods/ofxAddonLib#how-to-use-an-addon-which-uses-ofxaddonlib-pattern
